"""spare_parts_phase_3_receiving

Revision ID: 50176a0ab80f
Revises: c5742085e956
Create Date: 2026-10-04 16:28:46.976040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50176a0ab80f'
down_revision: Union[str, Sequence[str], None] = 'c5742085e956'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spare_purchase', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('spare_purchase', sa.Column('docket_reference', sa.String(length=100), nullable=True))
    op.add_column('spare_purchase', sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('spare_purchase', sa.Column('tax_total', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('spare_purchase', sa.Column('additional_charges', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('spare_purchase', sa.Column('landed_cost_total', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('spare_purchase', sa.Column('invoice_document_id', sa.String(length=100), nullable=True))
    op.add_column('spare_purchase', sa.Column('verification_status', sa.String(length=50), nullable=True))
    op.add_column('spare_purchase_item', sa.Column('part_code', sa.String(length=100), nullable=True))
    op.add_column('spare_purchase_item', sa.Column('part_description', sa.String(length=255), nullable=True))
    op.add_column('spare_purchase_item', sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('spare_purchase_item', sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('spare_purchase_item', sa.Column('verification_status', sa.String(length=50), nullable=False))
    op.add_column('spare_purchase_item', sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True))
    op.add_column('spare_purchase_item', sa.Column('variance_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.alter_column('spare_purchase_item', 'spare_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spare_purchase_item', 'spare_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('spare_purchase_item', 'variance_amount')
    op.drop_column('spare_purchase_item', 'confidence_score')
    op.drop_column('spare_purchase_item', 'verification_status')
    op.drop_column('spare_purchase_item', 'tax_amount')
    op.drop_column('spare_purchase_item', 'discount')
    op.drop_column('spare_purchase_item', 'part_description')
    op.drop_column('spare_purchase_item', 'part_code')
    op.drop_column('spare_purchase', 'verification_status')
    op.drop_column('spare_purchase', 'invoice_document_id')
    op.drop_column('spare_purchase', 'landed_cost_total')
    op.drop_column('spare_purchase', 'additional_charges')
    op.drop_column('spare_purchase', 'tax_total')
    op.drop_column('spare_purchase', 'subtotal')
    op.drop_column('spare_purchase', 'docket_reference')
    op.drop_column('spare_purchase', 'status')
    # ### end Alembic commands ###
