"""Add InventoryTag model

Revision ID: 5c42b07abd78
Revises: b63e80ce6a9c
Create Date: 2026-10-04 20:46:15.940115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c42b07abd78'
down_revision: Union[str, Sequence[str], None] = 'b63e80ce6a9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_inventory_tag',
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_identifier', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('tracking_mode', sa.String(length=20), nullable=False),
    sa.Column('spare_id', sa.BigInteger(), nullable=False),
    sa.Column('batch_id', sa.BigInteger(), nullable=True),
    sa.Column('serial_id', sa.BigInteger(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('last_printed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('print_count', sa.Integer(), nullable=False),
    sa.Column('revoked_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('restored_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('restored_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['module_spare_batch.batch_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['staff.staff_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['staff.staff_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['restored_by'], ['staff.staff_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['serial_id'], ['module_spare_serial.serial_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['spare_id'], ['module_spare_master.spare_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['staff.staff_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('tag_id'),
    sa.UniqueConstraint('tag_identifier')
    )
    op.create_index('idx_mod_inv_tag_batch', 'module_inventory_tag', ['batch_id'], unique=False)
    op.create_index('idx_mod_inv_tag_identifier', 'module_inventory_tag', ['tag_identifier'], unique=True)
    op.create_index('idx_mod_inv_tag_serial', 'module_inventory_tag', ['serial_id'], unique=False)
    op.create_index('idx_mod_inv_tag_spare', 'module_inventory_tag', ['spare_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_mod_inv_tag_spare', table_name='module_inventory_tag')
    op.drop_index('idx_mod_inv_tag_serial', table_name='module_inventory_tag')
    op.drop_index('idx_mod_inv_tag_identifier', table_name='module_inventory_tag')
    op.drop_index('idx_mod_inv_tag_batch', table_name='module_inventory_tag')
    op.drop_table('module_inventory_tag')
    # ### end Alembic commands ###
