"""extend_service_consumption

Revision ID: 6e1c02f7b170
Revises: b95b8de4113d
Create Date: 2026-10-04 21:46:32.367714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e1c02f7b170'
down_revision: Union[str, Sequence[str], None] = 'b95b8de4113d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spare_consumption', sa.Column('tracking_mode', sa.String(length=20), nullable=False))
    op.add_column('spare_consumption', sa.Column('batch_id', sa.BigInteger(), nullable=True))
    op.add_column('spare_consumption', sa.Column('part_code_snapshot', sa.String(length=100), nullable=True))
    op.add_column('spare_consumption', sa.Column('description_snapshot', sa.String(length=255), nullable=True))
    op.add_column('spare_consumption', sa.Column('unit_cost_snapshot', sa.Float(), nullable=True))
    op.add_column('spare_consumption', sa.Column('total_cost', sa.Float(), nullable=True))
    op.add_column('spare_consumption', sa.Column('consumed_by', sa.BigInteger(), nullable=True))
    op.add_column('spare_consumption', sa.Column('consumed_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('spare_consumption', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('spare_consumption', sa.Column('stock_movement_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_spare_consumption_batch_id'), 'spare_consumption', ['batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spare_consumption_batch_id'), table_name='spare_consumption')
    op.drop_column('spare_consumption', 'stock_movement_id')
    op.drop_column('spare_consumption', 'status')
    op.drop_column('spare_consumption', 'consumed_at')
    op.drop_column('spare_consumption', 'consumed_by')
    op.drop_column('spare_consumption', 'total_cost')
    op.drop_column('spare_consumption', 'unit_cost_snapshot')
    op.drop_column('spare_consumption', 'description_snapshot')
    op.drop_column('spare_consumption', 'part_code_snapshot')
    op.drop_column('spare_consumption', 'batch_id')
    op.drop_column('spare_consumption', 'tracking_mode')
    # ### end Alembic commands ###
