"""phase4_inventory

Revision ID: b3d3902563ee
Revises: 50176a0ab80f
Create Date: 2026-10-04 17:44:02.358458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3d3902563ee'
down_revision: Union[str, Sequence[str], None] = '50176a0ab80f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_spare_batch',
    sa.Column('batch_id', sa.BigInteger(), nullable=False),
    sa.Column('spare_id', sa.BigInteger(), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('received_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('expiry_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('restored_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('restored_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['staff.staff_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['staff.staff_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['restored_by'], ['staff.staff_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['spare_id'], ['module_spare_master.spare_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['staff.staff_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_index('idx_mod_spare_batch_no', 'module_spare_batch', ['batch_number'], unique=False)
    op.create_index('idx_mod_spare_batch_spare', 'module_spare_batch', ['spare_id'], unique=False)
    op.create_table('module_spare_stock_balance',
    sa.Column('balance_id', sa.BigInteger(), nullable=False),
    sa.Column('spare_id', sa.BigInteger(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['staff.staff_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['spare_id'], ['module_spare_master.spare_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['staff.staff_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('balance_id')
    )
    op.create_index('idx_mod_spare_stock_bal_spare_loc', 'module_spare_stock_balance', ['spare_id', 'location'], unique=True)
    op.add_column('module_spare_serial', sa.Column('location', sa.String(length=100), nullable=True))
    op.add_column('module_spare_serial', sa.Column('status', sa.String(length=30), nullable=False))
    op.add_column('module_spare_serial', sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('module_spare_stock_movement', sa.Column('batch_id', sa.BigInteger(), nullable=True))
    op.add_column('module_spare_stock_movement', sa.Column('from_location', sa.String(length=100), nullable=True))
    op.add_column('module_spare_stock_movement', sa.Column('to_location', sa.String(length=100), nullable=True))
    op.add_column('module_spare_stock_movement', sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('module_spare_stock_movement', sa.Column('total_cost', sa.Numeric(precision=14, scale=2), nullable=True))
    op.create_foreign_key(None, 'module_spare_stock_movement', 'module_spare_batch', ['batch_id'], ['batch_id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'module_spare_stock_movement', type_='foreignkey')
    op.drop_column('module_spare_stock_movement', 'total_cost')
    op.drop_column('module_spare_stock_movement', 'unit_cost')
    op.drop_column('module_spare_stock_movement', 'to_location')
    op.drop_column('module_spare_stock_movement', 'from_location')
    op.drop_column('module_spare_stock_movement', 'batch_id')
    op.drop_column('module_spare_serial', 'unit_cost')
    op.drop_column('module_spare_serial', 'status')
    op.drop_column('module_spare_serial', 'location')
    op.drop_index('idx_mod_spare_stock_bal_spare_loc', table_name='module_spare_stock_balance')
    op.drop_table('module_spare_stock_balance')
    op.drop_index('idx_mod_spare_batch_spare', table_name='module_spare_batch')
    op.drop_index('idx_mod_spare_batch_no', table_name='module_spare_batch')
    op.drop_table('module_spare_batch')
    # ### end Alembic commands ###
