"""phase4_wac_cost

Revision ID: b63e80ce6a9c
Revises: b3d3902563ee
Create Date: 2026-10-04 20:08:30.145656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b63e80ce6a9c'
down_revision: Union[str, Sequence[str], None] = 'b3d3902563ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module_spare_cost_history', sa.Column('wac_cost', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('module_spare_cost_history', 'wac_cost')
    # ### end Alembic commands ###
