"""Add SpareSale models

Revision ID: b95b8de4113d
Revises: 5c42b07abd78
Create Date: 2026-10-04 21:06:37.338079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b95b8de4113d'
down_revision: Union[str, Sequence[str], None] = '5c42b07abd78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spare_sale',
    sa.Column('sale_id', sa.BigInteger(), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by_staff_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('restored_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('restored_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['staff.staff_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['staff.staff_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['restored_by'], ['staff.staff_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['staff.staff_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('sale_id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_table('spare_sale_item',
    sa.Column('sale_item_id', sa.BigInteger(), nullable=False),
    sa.Column('sale_id', sa.BigInteger(), nullable=False),
    sa.Column('spare_id', sa.BigInteger(), nullable=False),
    sa.Column('part_code', sa.String(length=50), nullable=False),
    sa.Column('spare_name', sa.String(length=255), nullable=False),
    sa.Column('tracking_mode', sa.String(length=20), nullable=False),
    sa.Column('batch_id', sa.BigInteger(), nullable=True),
    sa.Column('serial_id', sa.BigInteger(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_selling_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('restored_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('restored_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['staff.staff_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['staff.staff_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['restored_by'], ['staff.staff_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sale_id'], ['spare_sale.sale_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['staff.staff_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('sale_item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spare_sale_item')
    op.drop_table('spare_sale')
    # ### end Alembic commands ###
