"""spare_parts_phase_2_pricing

Revision ID: c5742085e956
Revises: fac5282b36be
Create Date: 2026-10-04 16:14:37.656808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5742085e956'
down_revision: Union[str, Sequence[str], None] = 'fac5282b36be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_price_list',
    sa.Column('price_list_id', sa.BigInteger(), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('restored_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('restored_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['staff.staff_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['staff.staff_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['restored_by'], ['staff.staff_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['staff.staff_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('price_list_id')
    )
    op.create_table('module_price_list_version',
    sa.Column('version_id', sa.BigInteger(), nullable=False),
    sa.Column('price_list_id', sa.BigInteger(), nullable=False),
    sa.Column('version_reference', sa.String(length=100), nullable=False),
    sa.Column('effective_from', sa.TIMESTAMP(), nullable=False),
    sa.Column('received_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('restored_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('restored_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['staff.staff_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['staff.staff_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['price_list_id'], ['module_price_list.price_list_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restored_by'], ['staff.staff_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['staff.staff_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_index('idx_mod_price_list_version', 'module_price_list_version', ['price_list_id'], unique=False)
    op.create_table('module_spare_cost_history',
    sa.Column('cost_id', sa.BigInteger(), nullable=False),
    sa.Column('spare_id', sa.BigInteger(), nullable=False),
    sa.Column('effective_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('billed_unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('additional_costs', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('landed_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('source_reference', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('restored_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('restored_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['staff.staff_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['staff.staff_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['restored_by'], ['staff.staff_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['spare_id'], ['module_spare_master.spare_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['staff.staff_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('cost_id')
    )
    op.create_index('idx_mod_spare_cost_spare', 'module_spare_cost_history', ['spare_id'], unique=False)
    op.create_table('module_spare_selling_price_history',
    sa.Column('price_id', sa.BigInteger(), nullable=False),
    sa.Column('spare_id', sa.BigInteger(), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('effective_from', sa.TIMESTAMP(), nullable=False),
    sa.Column('effective_to', sa.TIMESTAMP(), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('restored_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('restored_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['staff.staff_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['staff.staff_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['restored_by'], ['staff.staff_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['spare_id'], ['module_spare_master.spare_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['staff.staff_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('price_id')
    )
    op.create_index('idx_mod_spare_selling_price_spare', 'module_spare_selling_price_history', ['spare_id'], unique=False)
    op.create_table('module_price_list_item',
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('version_id', sa.BigInteger(), nullable=False),
    sa.Column('part_code', sa.String(length=50), nullable=False),
    sa.Column('part_name', sa.String(length=150), nullable=True),
    sa.Column('mrp', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('dlp', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('restored_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('restored_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['staff.staff_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['staff.staff_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['restored_by'], ['staff.staff_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['staff.staff_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['version_id'], ['module_price_list_version.version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index('idx_mod_price_list_item_code', 'module_price_list_item', ['part_code'], unique=False)
    op.create_index('idx_mod_price_list_item_version', 'module_price_list_item', ['version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_mod_price_list_item_version', table_name='module_price_list_item')
    op.drop_index('idx_mod_price_list_item_code', table_name='module_price_list_item')
    op.drop_table('module_price_list_item')
    op.drop_index('idx_mod_spare_selling_price_spare', table_name='module_spare_selling_price_history')
    op.drop_table('module_spare_selling_price_history')
    op.drop_index('idx_mod_spare_cost_spare', table_name='module_spare_cost_history')
    op.drop_table('module_spare_cost_history')
    op.drop_index('idx_mod_price_list_version', table_name='module_price_list_version')
    op.drop_table('module_price_list_version')
    op.drop_table('module_price_list')
    # ### end Alembic commands ###
