"""spare_parts_phase_1

Revision ID: fac5282b36be
Revises: 191eb4aa4173
Create Date: 2026-10-04 15:17:16.313178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fac5282b36be'
down_revision: Union[str, Sequence[str], None] = '191eb4aa4173'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_spare_part_code',
    sa.Column('code_id', sa.BigInteger(), nullable=False),
    sa.Column('spare_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.TIMESTAMP(), nullable=False),
    sa.Column('effective_to', sa.TIMESTAMP(), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('restored_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('restored_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['staff.staff_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['staff.staff_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['restored_by'], ['staff.staff_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['spare_id'], ['module_spare_master.spare_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['staff.staff_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('code_id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('module_spare_part_vehicle_compatibility',
    sa.Column('compatibility_id', sa.BigInteger(), nullable=False),
    sa.Column('spare_id', sa.BigInteger(), nullable=False),
    sa.Column('vehicle_model_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['staff.staff_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['spare_id'], ['module_spare_master.spare_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['staff.staff_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('compatibility_id')
    )
    op.create_index('idx_mod_spare_veh_compat', 'module_spare_part_vehicle_compatibility', ['spare_id', 'vehicle_model_id'], unique=True)
    op.add_column('module_spare_master', sa.Column('tracking_mode', sa.String(length=20), nullable=True))
    op.add_column('module_spare_master', sa.Column('status', sa.String(length=20), nullable=True))
    
    # --- DATA MIGRATION ---
    # Convert is_serialized -> tracking_mode
    op.execute("UPDATE module_spare_master SET tracking_mode = 'SERIALIZED' WHERE is_serialized = true")
    op.execute("UPDATE module_spare_master SET tracking_mode = 'QUANTITY' WHERE is_serialized = false")
    
    # Set default status
    op.execute("UPDATE module_spare_master SET status = 'ACTIVE'")
    
    # Migrate spare_code to module_spare_part_code
    op.execute("""
        INSERT INTO module_spare_part_code (spare_id, code, is_current, effective_from, is_deleted, created_at)
        SELECT spare_id, spare_code, true, CURRENT_TIMESTAMP, false, CURRENT_TIMESTAMP
        FROM module_spare_master
    """)
    # ----------------------
    
    op.alter_column('module_spare_master', 'tracking_mode', nullable=False)
    op.alter_column('module_spare_master', 'status', nullable=False)

    # op.drop_constraint(op.f('module_spare_master_spare_code_key'), 'module_spare_master', type_='unique')
    # Use the actual constraint name from the DB (Alembic autogenerate might get the name wrong if naming convention isn't fully configured for drops on existing DBs, but let's stick to the autogenerated name or 'module_spare_master_spare_code_key')
    op.drop_constraint('module_spare_master_spare_code_key', 'module_spare_master', type_='unique')
    op.drop_column('module_spare_master', 'is_serialized')
    op.drop_column('module_spare_master', 'spare_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module_spare_master', sa.Column('spare_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('module_spare_master', sa.Column('is_serialized', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('module_spare_master_spare_code_key'), 'module_spare_master', ['spare_code'], postgresql_nulls_not_distinct=False)
    op.drop_column('module_spare_master', 'status')
    op.drop_column('module_spare_master', 'tracking_mode')
    op.drop_index('idx_mod_spare_veh_compat', table_name='module_spare_part_vehicle_compatibility')
    op.drop_table('module_spare_part_vehicle_compatibility')
    op.drop_table('module_spare_part_code')
    # ### end Alembic commands ###
